paths:
  /products:
    get:
      operationId: getProduct
      parameters:
      - name: "guid"
        in: "query"
        required: true
        type: number
        description: "Global Unique IDentity"
      responses:
        200:
          description: "Status 200"
          schema:
            type: object
            properties:
              product:
                $ref: "#/definitions/Product"
              categories:
                type: array
                items:
                  $ref: "#/definitions/Category"
              shop:
                $ref: "#/definitions/Shop"  
    post:
      operationId: getProducts
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          type: "object"
          properties:
            category_guid:
              type: number
            shop_guid:
              type: number
              description: "if category_guid and shop_guid is null return false"
            type_product:
              type: string
              description: "example:\n  null: get all product\n  default: get normal product\
                \ normal\n  featured: get product featured\n  voucher: get product\
                \ voucher\n  ticket: get product ticket"
            product_filter:
              type: number
              description: "infused product group"
            get_all:
              type: number
              description: "0: loadmore \n 1: get all product"
            offset:
              type: number
            limit:
              type: number
      responses:
        200:
          description: "Status 200"
          schema:
            type: object
            properties:
              products:
                type: array
                items:
                  $ref: "#/definitions/Product"
              categories:
                type: array
                items:
                  $ref: "#/definitions/Category"
    put:
      operationId: createProduct
      consumes: []
      parameters:
      - name: body
        in: body
        required: true
        schema:
          type: object
          properties:
            sku:
              type: string
            storage_duration:
              type: string
            title:
              type: string
            description:
              type: string
            manufacturer:
              type: string
            is_special:
              type: number
            voucher_category:
              type: number
            ticket_category:
              type: number
            tax:
              type: number
            price:
              type: number
            currency:
              type: string
            quantity:
              type: number
            weight:
              type: number
            product_group:
              type: number
            featured:
              type: number
            expiry:
              type: number
            duration:
              type: number
            begin_day:
              type: string
            end_day:
              type: string
            friendly_url:
              type: string
            origin:
              type: string
            order:
              type: string
            status:
              type: string
            ossn_photo:
              type: array
              items:
                type: string
            shop_category:
              type: array
              items:
                type: string
            market_category:
              type: array
              items:
                type: string
            custom_attribute_keys:
              type: array
              items:
                type: string
            custom_attribute_values:
              type: array
              items:
                type: string
            images:
              type: array
              items:
                type: string
            unit:
              type: string
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/DefaultResponse"
    patch:
      operationId: updateProduct
      consumes: []
      parameters:
      - name: body
        in: body
        required: true
        schema:
          type: object
          properties:
            product_guid:
              type: number
            sku:
              type: string
            title:
              type: string
            description:
              type: string
            manufacturer:
              type: string
            is_special:
              type: number
            voucher_category:
              type: number
            ticket_category:
              type: number
            tax:
              type: number
            price:
              type: number
            currency:
              type: string
            quantity:
              type: number
            expiry:
              type: number
            duration:
              type: number
            begin_day:
              type: string
            end_day:
              type: string
            friendly_url:
              type: string
            origin:
              type: string
            order:
              type: string
            weight:
              type: number
            storage_duration:
              type: number
            product_group:
              type: number
            featured:
              type: number
            status:
              type: string
            ossn_photo:
              type: array
              items:
                type: string
            shop_category:
              type: array
              items:
                type: string
            market_category:
              type: array
              items:
                type: string
            custom_attribute_keys:
              type: array
              items:
                type: string
            custom_attribute_values:
              type: array
              items:
                type: string
            images:
              type: array
              items:
                type: string
            unit:
              type: string
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/DefaultResponse"
    delete:
      operationId: deleteProduct
      description: ""
      parameters:
      - name: "product_guid"
        in: "query"
        required: true
        type: number
        description: "Global Unique IDentity"
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/DefaultResponse"
