swagger: "2.0"
info:
  version: "0.0.1"
  title: Amely API
host: dev.helloqua.com
basePath: /ws/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
securityDefinitions:
  user_token:
    type: "apiKey"
    name: "auth_token"
    in: "query"
definitions:
